repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.9.1
  hooks:
    - id: black
      language_version: python3.10

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort

- repo: local
  hooks:
    - id: run-python-script
      name: Generate Documentation
      entry: python generate_api_docs.py
      language: system
      stages: [commit]
