[tool.poetry]
name = "trajectopy"
version = "2.0.0"
description = "Trajectory Evaluation in Python"
authors = ["Gereon Tombrink <tombrink@igg.uni-bonn.de>"]
maintainers = ["Gereon Tombrink <tombrink@igg.uni-bonn.de>"]
license = "GPLv3"
keywords = ["trajectory", "evaluation", "alignment", "similarity", "leverarm", "epsg", "robotics"]
readme = "README.md"
homepage = "https://github.com/gereon-t/trajectopy"
repository = "https://github.com/gereon-t/trajectopy.git"
packages = [
    { include = "trajectopy" },
]

[tool.poetry.dependencies]
python = ">=3.9.0,<3.12"
PyQt6 = ">=6.5.2"
PyQt6-Qt6 = ">=6.5.2"
PyQt6-sip = ">=13.5.2"
rich = "^13.5.3"
matplotlib = "^3.7.3"
trajectopy-core = "^2.4.0"
rosbags = "^0.9.16"

[tool.poetry.scripts]
trajectopy = "trajectopy.__main__:main"

[tool.poetry.group.dev.dependencies]
mypy = "^1.5.1"
black = "^23.9.1"
pre-commit = "^3.5.0"

[tool.isort]
profile = "black"
line_length = 119

[tool.black]
line-length = 119

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"